### ISSUE TITLE
Lua access to current buffer position

### ISSUE THREAD

**Issue by expertsleepers** [expertsleepersltd/issues#117]

**Comment by expertsleepers** [comment]
[ExSlAugustusLoop.component.zip](https://github.com/expertsleepersltd/issues/files/5245883/ExSlAugustusLoop.component.zip)

**Comment by expertsleepers** [comment]
Tested with e.g.

	if noteNumber == 60 then
		bufferPos = getBufferPosition()
		print( "get buffer:", bufferPos )	
	end
	if noteNumber == 62 then
		setBufferPosition( bufferPos )
		print( "set buffer:", bufferPos )	
	end

**Comment by greencubeCH** [comment]
Dear Andrew / Expertsleepers:
I am trying to access the buffer position in a Lua-script for Augustus loop but it seems that this feature is not implemented in my version of the plugin - 2.5.7 - can that be?
I am sadly not able to get the .component available in this thread to work under Big Sur on a mac due to security issues I guess. I would very much appreciate your help with this, thanks.

https://github.com/expertsleepersltd/issues/issues/117#issuecomment-694878843
