### ISSUE TITLE
quad quantiser

### ISSUE THREAD

**Issue by expertsleepers** [expertsleepersltd/issues#418]
With per-output slew.

**Comment by expertsleepers** [comment]
Chord Engine added for 1.14, but there's probably a case for a more straightforward quad quantiser, so leaving this open.

**Comment by expertsleepers** [comment]
Also https://modwiggler.com/forum/viewtopic.php?p=3866400#p3866400

**Comment by expertsleepers** [comment]
Use calibration from chord engine etc.

https://www.modwiggler.com/forum/viewtopic.php?p=3903823#p3903823

**Comment by expertsleepers** [comment]
https://www.modwiggler.com/forum/viewtopic.php?p=4070897#p4070897

**Comment by expertsleepers** [comment]
Quantize to MIDI notes:
https://modwiggler.com/forum/viewtopic.php?p=4071535#p4071535

**Comment by expertsleepers** [comment]
[distingEX_1.24beta.hex.zip](https://github.com/expertsleepersltd/issues/files/13503249/distingEX_1.24beta.hex.zip)

**Comment by nealsanche** [comment]
I spent some time with Quad Quantiser the other day, and tonight. Some thoughts, and I hope it's alright to leave them here:

* I found it strange that 12TET isn't the default initial calibration, or I did it wrong. When I set this, and calibrated again, things sounded more rational to me.
* Calibration isn't working all that well for me. I almost wish that the tuning algorithm used the same better algorithm present in the Tuner, because I regularly get jagged lines if I am trying to calibrate square waves. Sawtooth waves don't seem to work at all. Though I understand having things the same as the chord engine. Maybe all of the Disting algorithms could share the same tuning algorithm with the Tuner.

I admit I haven't tried doing much with it yet. I have thought I'd like to add the prometheus scale to this, but I don't really know how to go about it. Scala files, maybe. I'll look into it.

**Comment by expertsleepers** [comment]
- 12TET should be the default, if you don't use MTS or Scala.
- Square and saw waves work fine for me. Where are your waves coming from? Can you post a recording of how they sound during calibration?

**Comment by nealsanche** [comment]
The Wavs are coming from Arp2600m OSC 1, 2 and 3. I find the only oscillator that is super easy for the calibrator to handle is the OSC2 sine wave. I'll make a recording and drop it for you, of the sound of the thing calibrating.

**Comment by nealsanche** [comment]
Here's where I put the two files:

https://drive.google.com/drive/folders/15ctrIxDYiJY89bcHAHpFhmA4vvtyDVNI?usp=sharing

When I use the Saw oscillator output, the Calibrator seems to go at half speed. Probably because it's not locking on to whatever it is listening to.

As sampled through the ES-8, the Saw looks like this: 
![Screenshot 2023-12-07 at 9 46 28 PM](https://github.com/expertsleepersltd/issues/assets/5369033/5567ddf6-29f9-47da-af3c-9000bca3985d)

 and the Square is:
![Screenshot 2023-12-07 at 9 47 38 PM](https://github.com/expertsleepersltd/issues/assets/5369033/dd607655-53e0-48c1-befb-12029dbba610)

**Comment by nealsanche** [comment]
I think I see the issue. On OSC1, and I assume also OSC3, it seems that the waveform is Unipolar, from 0 to 10V. I never noticed that before. I'll probably have better luck if I can offset it, now to figure out how to get an offset out of this machine. OSC2 Sine, and OSC2 Triangle outputs are bipolar.

**Comment by nealsanche** [comment]
Okay, I figured out how to patch the 2600m to get a bipolar signal into Disting EX and I'm getting straight lines out of the calibration for those oscillators. So, this is good. I guess this is all just info for you, and learning for me. ;)
