### ISSUE TITLE
MIDI to I2C conversion

### ISSUE THREAD

**Issue by expertsleepers** [expertsleepersltd/issues#635]

**Comment by expertsleepers** [comment]
New setting under Settings -> MIDI/I2C page 2: 'Enable MIDI to I2C'

New submenu Settings -> MIDI To I2C

MIDI note on/off only are converted.

Note: disting EX i2c (follower) address defaults to 0x31, same as ER-301, so change it to something else.

[distingEX_1.20beta.hex.zip](https://github.com/expertsleepersltd/issues/files/11261813/distingEX_1.20beta.hex.zip)

**Comment by TrovarsiOfficial** [comment]
Great! Thanks for working on this. I'll download and try this today.

**Comment by expertsleepers** [comment]
New beta

- now does MIDI CC conversion as well.
- new note mode "gate per note" outputs gates to adjacent ports per key, ideal for e.g. lots of drum triggers.

[distingEX_1.20beta.hex.zip](https://github.com/expertsleepersltd/issues/files/11273670/distingEX_1.20beta.hex.zip)

**Comment by TrovarsiOfficial** [comment]
Hi Os, OK, so I downloaded the new beta and I was able to locate all the settings that you added. I connected it to the ER 301 as well. The part that’s a bit confusing is how to get it to talk to the ER 301 because the only way 301 can receive the information is through ports. I am speaking to this artist that uses the ER 301, but he sends information the reverse direction - 12c to Midi. I’m going to the get information from him regarding the ports access to the ER 301. Otherwise I’m not sure how they are supposed to fully communicate. Best regards,Shanda NunezArtist Name: TrovarsiCo-Founder of Southern California Synth SocietyWebsite - Trovarsi | Instagram | YouTube Channel | Facebook [Artist Page] | SoundCloud | Resident AdvisorOn Apr 19, 2023, at 6:39 AM, Andrew Ostler ***@***.***> wrote:﻿
New beta

now does MIDI CC conversion as well.
new note mode "gate per note" outputs gates to adjacent ports per key, ideal for e.g. lots of drum triggers.

distingEX_1.20beta.hex.zip

**Comment by expertsleepers** [comment]
Yes, that's what the disting is doing - sending the i2c commands that control ports. (Hence the settings for port numbers.)

It should be exactly equivalent to sending the supported Teletype commands (https://docs.orthogonaldevices.com/er-301/teletype-pkg/).
